### ISSUE TITLE
readName and readRefValue

### ISSUE THREAD

**Issue by thundernet8** [eleme/thrift-parser#17]
In `readName` method, the regexp is like `/[a-zA-Z0-9_\.]+/`, but I do think it's illegal for a `dot(.)` in a name string.
In `readRefValue` method `readName` is included and used firstly, and then you check dot(.) again which I think is not necessary if dot(.) is legal in `readName`.

e.g `namespace java com.company.service`
readScope() -> `java`
readRefValue(): 1. readName -> `com.company.service` 2. readChar('.') (for what ???)

**Comment by phated** [comment]
Scopes can be dot-separated.
